### ISSUE TITLE
Table view vanish when changing the chosen columns

### ISSUE THREAD

**Issue by michaelaye** [SETI/rms-opus#546] opened 2019-01-04 00:38 UTC
With this link:

https://tools.pds-rings.seti.org/opus/#/target=Dione&instrument=Cassini+UVIS&COUVISbandbin1=2&COUVISbandbin2=&COUVISchannel=FUV&view=browse&browse=data&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=planet,target,phase1,phase2,time1,COUVISbandbin1&widgets=COUVISchannel,COUVISbandbin1,instrument,planet,target&widgets2=&detail=

I don't see a table view currently. just blank.

It worked before I changed the chosen columns to show. It currently doesn't work even after resetting the search, so maybe I broke it? ;)

**Comment by rfrenchseti** [comment] 2019-01-05 22:50
The problem is that "OPUS ID" was removed as one of the columns. It currently must be there for the system to work. It's actually a little hard to remove it, because you can't hit the "X" over the column name. But it's possible by clicking on OPUS ID under the General Constraints menu and deselecting it there. If you go to Choose Columns and select OPUS ID again, it will start working.

The new UI doesn't require the OPUS ID to be one of the selected columns so this will get fixed when that is deployed.

Michael - Please note that "phase1" and "phase2" are deprecated slug names. You should be using RINGGEOphase1" and "RINGGEOphase2". This can only happen if you started with an old URL. I strongly suggest you always start with a clean OPUS so that you get the latest updates.

**Comment by michaelaye** [comment] 2019-01-05 23:12
Ok, yes, I had a saved bookmark from earlier times. It's very handy that search parameters CAN be stored in a bookmark though, that's another advantage of your system compared to other PDS search engines.

**Comment by rfrenchseti** [comment] 2019-01-05 23:19
Yep, absolutely! We work hard to make sure that the URL can be saved, and the old URL terms do still work. But they are ambiguous (like phase1 - phase of what? Rings? Surface geometry?) and sometimes there are even two totally different fields that have the same column name in the URL, which doesn't work very well. So we prefer to use the new, disambiguated names going forward to avoid such problems.

**Comment by rfrenchseti** [comment] 2019-01-06 00:46
This is a duplicate of #544

**Closed as completed by rfrenchseti** 2019-01-06 00:46 UTC
Labels: A-Bug, Priority 3 Important, Effort 2 Medium, B-OPUS Django
